# Generated by Django 4.0.5 on 2022-08-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ImageField(default=True, upload_to='post_profile'),
        ),
    ]
