# Generated by Django 4.0.5 on 2022-08-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ImageField(upload_to='post_profile'),
        ),
    ]
